### ISSUE TITLE
Flight dataframe left in add_gps_to_rayshader

### ISSUE THREAD

**Issue by nstrayer** [neilcharles/geoviz#2]
In trying to use `add_gps_to_rayshader` I got this error: 
```
Error in cbind(flight$long, rep(e@ymin, nrow(flight))) : 
  object 'flight' not found
```

Upon investigating it looks like an object `flight` was left in the code at [these lines](https://github.com/neilcharles/geoviz/blob/master/R/add_gps_to_rayshader.R#L30-L32). 

When I have some free time I can fix this up if you are too busy! 

Thanks for the fantastic library and inspiration for some visualizations!

**Comment by neilcharles** [comment]
Oops! Thanks, I'm working on a couple of new features so will push a fix today.

First thing I've built that's drawn enough attention for errors to get spotted :)
