### ISSUE TITLE
GPS tracks don't line up

### ISSUE THREAD

**Issue by meganwinton** [neilcharles/geoviz#34]
Super excited about using this package for visualizing fish tagging data but running into an issue where the tracks aren't lining up. Running the example also results in a map with the GPS track offset:

![GPSexample](https://user-images.githubusercontent.com/15893835/71818013-b7123a80-3055-11ea-8b7a-8e94fd4e014e.png)

Any thoughts on how to appropriately re-scale would be much appreciated!

**Comment by neilcharles** [comment]
Installing the dev version from github should fix it:
`devtools::install_github("neilcharles/geoviz")`

I'll push the change to CRAN soon. It happened because Rayshader was updated to use a different coordinate system.

**Comment by meganwinton** [comment]
Works beautifully now - thank you!!

**Comment by neilcharles** [comment]
Fixed by 0.2.2 on CRAN https://github.com/neilcharles/geoviz/releases/tag/0.2.2
