### ISSUE TITLE
choroplet: not able to render my first test

### ISSUE THREAD

**Issue by aborruso** [neilcharles/geoviz#43]
Hi,
and thank you for this great tool.

I'm trying to take the first steps, and I started with this coropletic map:
<https://observablehq.com/d/cea3c118d5fac39b>

It should be a world map, but in the rendering I see a colored background and a small polygon with a white outline.

What am I doing wrong?

Thank you

**Comment by neocarto** [comment]
This is a rewind issue.
Try viz.tool.rewind(nazionalita)

**Comment by aborruso** [comment]
> This is a rewind issue. Try viz.tool.rewind(nazionalita)

Thank you very much, I think I have used QGIS to create it. What tool can I use to normalize a geojson? Mapshaper?

Now I have another problem: I can see the map, but is it all one color. Why is the color scale not applied to the "Valore" field?

Thank you again

**Comment by aborruso** [comment]
I have changed method, and it works.

Ok I must study "How to choose a method?"
